Add get endpoint
gosearch/gosearch pull request #1
Opened 2016-11-16 06:25 UTC by simon0191

- Simplify router
- Change `POST /{index}` to `POST /{index}/{id}` and receive data as JSON to match elastic search API
- Add GET /{index}/{id} endpoint

2016-11-17 02:39 UTC, 0x5d requested changes

2016-11-17 02:39 UTC, castillobgr commented on http/http.go
> +	router.HandleFunc("/{index}/{id}", createIndex(server.Index)).Methods(http.MethodPost)
This should still be prefixed by something like `/index` or `/api/index`, for namespacing.

2016-11-17 02:39 UTC, castillobgr commented on http/http.go
> -			http.Error(w, "No index was specified.", http.StatusBadRequest)
Why remove the `http.Error`?

2016-11-17 02:39 UTC, castillobgr commented on http/http.go
> +func showIndex(indexService service.IndexService) http.HandlerFunc {
Consider renaming this to `GetIndex`, "show" is a little misleading.

2016-11-17 02:39 UTC, castillobgr commented on service/index.go
> +		index, err := bleve.New(".db/"+indexName, mapping)
This should probably be configurable. Maybe not right now, tho.

2016-11-17 02:39 UTC, castillobgr commented on service/index.go
> +			log.Fatal(err)
We should handle logs with [logrus](https://github.com/Sirupsen/logrus) or something more robust and configurable, to be able to disable it and have different log levels.

2016-11-17 02:39 UTC, castillobgr commented on http/http.go
> +		index := vars["index"]
This is way cleaner :smile:

2016-11-17 02:57 UTC, castillobgr commented on service/index.go
> +	index, err := openOrCreateIndex(indexName)
I don't agree with nonexistent indices being created upon attempting to query them.

2016-11-17 04:27 UTC, simon0191 commented on http/http.go
> +	router.HandleFunc("/{index}/{id}", createIndex(server.Index)).Methods(http.MethodPost)
We should discuss if we want to be as similar as possible to elastic search. If yes, the elastic search API doesn't use an api nor index prefix in their routes, if no, I agree with you, we should prefix the routes with `/api`.

2016-11-17 04:28 UTC, simon0191 commented on http/http.go
> -			http.Error(w, "No index was specified.", http.StatusBadRequest)
If there's no index specified the server will automatically respond 404 because there's no route that matches the path.

2016-11-17 04:28 UTC, simon0191 commented on http/http.go
> +		index := vars["index"]
:D

2016-11-17 04:28 UTC, simon0191 commented on http/http.go
> +func showIndex(indexService service.IndexService) http.HandlerFunc {
👍

2016-11-17 04:28 UTC, simon0191 commented on service/index.go
> +		index, err := bleve.New(".db/"+indexName, mapping)
👍

2016-11-17 04:28 UTC, simon0191 commented on service/index.go
> +			log.Fatal(err)
👍

2016-11-17 04:28 UTC, simon0191 commented on service/index.go
> +	index, err := openOrCreateIndex(indexName)
👍

2016-11-17 21:01 UTC, c4milo commented on http/http.go
> +	router.HandleFunc("/{index}/{id}", createIndex(server.Index)).Methods(http.MethodPost)
I wouldn't mind a compatibility lawyer with ElasticSearch's API

2016-11-17 21:02 UTC, c4milo commented on http/http.go
> +func showIndex(indexService service.IndexService) http.HandlerFunc {
It could also just be just `Index`

2016-11-17 21:04 UTC, c4milo commented on service/index.go
> +		index, err := bleve.New(".db/"+indexName, mapping)
`filepath.Join` is more portable.

2016-11-17 21:29 UTC, castillobgr commented on http/http.go
> +func showIndex(indexService service.IndexService) http.HandlerFunc {
@c4milo That would also be ambiguous (index could also refer to the action of indexing a document).

2016-11-22 17:52 UTC, c4milo commented on http/http.go
> +	"reflect"
reflect package is only really needed when decoding or decoding protocols into Go's struct types. Other than that is usually considered non-idiomatic and in some cases a bad practice. There is some history to it already: https://codegangsta.io/blog/2014/05/19/my-thoughts-on-martini/

2016-11-24 22:54 UTC, merged